/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrademarkRouteImport } from './routes/trademark'
import { Route as StartupNetworkRouteImport } from './routes/startup-network'
import { Route as StartupIndiaRouteImport } from './routes/startup-india'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LlpRegistrationRouteImport } from './routes/llp-registration'
import { Route as LegalComplianceRouteImport } from './routes/legal-compliance'
import { Route as GstRegistrationRouteImport } from './routes/gst-registration'
import { Route as FundraisingRouteImport } from './routes/fundraising'
import { Route as FinanceTaxRouteImport } from './routes/finance-tax'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRegistrationRouteImport } from './routes/company-registration'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TrademarkRoute = TrademarkRouteImport.update({
  id: '/trademark',
  path: '/trademark',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupNetworkRoute = StartupNetworkRouteImport.update({
  id: '/startup-network',
  path: '/startup-network',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupIndiaRoute = StartupIndiaRouteImport.update({
  id: '/startup-india',
  path: '/startup-india',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LlpRegistrationRoute = LlpRegistrationRouteImport.update({
  id: '/llp-registration',
  path: '/llp-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalComplianceRoute = LegalComplianceRouteImport.update({
  id: '/legal-compliance',
  path: '/legal-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const GstRegistrationRoute = GstRegistrationRouteImport.update({
  id: '/gst-registration',
  path: '/gst-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingRoute = FundraisingRouteImport.update({
  id: '/fundraising',
  path: '/fundraising',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTaxRoute = FinanceTaxRouteImport.update({
  id: '/finance-tax',
  path: '/finance-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRegistrationRoute = CompanyRegistrationRouteImport.update({
  id: '/company-registration',
  path: '/company-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/company-registration': typeof CompanyRegistrationRoute
  '/contact': typeof ContactRoute
  '/finance-tax': typeof FinanceTaxRoute
  '/fundraising': typeof FundraisingRoute
  '/gst-registration': typeof GstRegistrationRoute
  '/legal-compliance': typeof LegalComplianceRoute
  '/llp-registration': typeof LlpRegistrationRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startup-india': typeof StartupIndiaRoute
  '/startup-network': typeof StartupNetworkRoute
  '/trademark': typeof TrademarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/company-registration': typeof CompanyRegistrationRoute
  '/contact': typeof ContactRoute
  '/finance-tax': typeof FinanceTaxRoute
  '/fundraising': typeof FundraisingRoute
  '/gst-registration': typeof GstRegistrationRoute
  '/legal-compliance': typeof LegalComplianceRoute
  '/llp-registration': typeof LlpRegistrationRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startup-india': typeof StartupIndiaRoute
  '/startup-network': typeof StartupNetworkRoute
  '/trademark': typeof TrademarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/company-registration': typeof CompanyRegistrationRoute
  '/contact': typeof ContactRoute
  '/finance-tax': typeof FinanceTaxRoute
  '/fundraising': typeof FundraisingRoute
  '/gst-registration': typeof GstRegistrationRoute
  '/legal-compliance': typeof LegalComplianceRoute
  '/llp-registration': typeof LlpRegistrationRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startup-india': typeof StartupIndiaRoute
  '/startup-network': typeof StartupNetworkRoute
  '/trademark': typeof TrademarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/company-registration'
    | '/contact'
    | '/finance-tax'
    | '/fundraising'
    | '/gst-registration'
    | '/legal-compliance'
    | '/llp-registration'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/startup-india'
    | '/startup-network'
    | '/trademark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/company-registration'
    | '/contact'
    | '/finance-tax'
    | '/fundraising'
    | '/gst-registration'
    | '/legal-compliance'
    | '/llp-registration'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/startup-india'
    | '/startup-network'
    | '/trademark'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/company-registration'
    | '/contact'
    | '/finance-tax'
    | '/fundraising'
    | '/gst-registration'
    | '/legal-compliance'
    | '/llp-registration'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/startup-india'
    | '/startup-network'
    | '/trademark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompanyRegistrationRoute: typeof CompanyRegistrationRoute
  ContactRoute: typeof ContactRoute
  FinanceTaxRoute: typeof FinanceTaxRoute
  FundraisingRoute: typeof FundraisingRoute
  GstRegistrationRoute: typeof GstRegistrationRoute
  LegalComplianceRoute: typeof LegalComplianceRoute
  LlpRegistrationRoute: typeof LlpRegistrationRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartupIndiaRoute: typeof StartupIndiaRoute
  StartupNetworkRoute: typeof StartupNetworkRoute
  TrademarkRoute: typeof TrademarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trademark': {
      id: '/trademark'
      path: '/trademark'
      fullPath: '/trademark'
      preLoaderRoute: typeof TrademarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup-network': {
      id: '/startup-network'
      path: '/startup-network'
      fullPath: '/startup-network'
      preLoaderRoute: typeof StartupNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup-india': {
      id: '/startup-india'
      path: '/startup-india'
      fullPath: '/startup-india'
      preLoaderRoute: typeof StartupIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llp-registration': {
      id: '/llp-registration'
      path: '/llp-registration'
      fullPath: '/llp-registration'
      preLoaderRoute: typeof LlpRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-compliance': {
      id: '/legal-compliance'
      path: '/legal-compliance'
      fullPath: '/legal-compliance'
      preLoaderRoute: typeof LegalComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-registration': {
      id: '/gst-registration'
      path: '/gst-registration'
      fullPath: '/gst-registration'
      preLoaderRoute: typeof GstRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising': {
      id: '/fundraising'
      path: '/fundraising'
      fullPath: '/fundraising'
      preLoaderRoute: typeof FundraisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-tax': {
      id: '/finance-tax'
      path: '/finance-tax'
      fullPath: '/finance-tax'
      preLoaderRoute: typeof FinanceTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-registration': {
      id: '/company-registration'
      path: '/company-registration'
      fullPath: '/company-registration'
      preLoaderRoute: typeof CompanyRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompanyRegistrationRoute: CompanyRegistrationRoute,
  ContactRoute: ContactRoute,
  FinanceTaxRoute: FinanceTaxRoute,
  FundraisingRoute: FundraisingRoute,
  GstRegistrationRoute: GstRegistrationRoute,
  LegalComplianceRoute: LegalComplianceRoute,
  LlpRegistrationRoute: LlpRegistrationRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartupIndiaRoute: StartupIndiaRoute,
  StartupNetworkRoute: StartupNetworkRoute,
  TrademarkRoute: TrademarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
